language: php

addons:
  postgresql: "12"
  apt:
    packages:
      - postgresql-12
      - postgresql-client-12

services:
  - mysql
  - docker

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

php:
 - 7.4

env:
  global:
    - PGVER=12
    - IGNORE_PATHS=ignore
    - IGNORE_NAMES=ignore_name.php
    - MUSTACHE_IGNORE_NAMES=broken.mustache
    - DB=pgsql
    - MOODLE_BRANCH=master

before_install:
  # We want to verify that xdebug works for coverage. Once we only support
  # Moodle 3.10/PHPUnit 8 and up, we can switch our tests to pcov too.
  # - phpenv config-rm xdebug.ini
  - make init
  # Mimic how a Moodle plugin would be run.
  - cp -R tests/Fixture/moodle-local_ci ../moodle-local_ci
  - export PATH="$(cd bin; pwd):$(cd vendor/bin; pwd):$PATH"
  - export TRAVIS_BUILD_DIR=$(cd ../moodle-local_ci; pwd)
  - >
    if [ -n "$DOCKER_USER" ] && [ -n "$DOCKER_TOKEN" ]; then
        echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_USER" --password-stdin
        echo "Using authenticated connection (no pull limits)"
    else
        echo "Using unauthenticated docker (pull limits may apply). Setup DOCKER_USER and DOCKER_TOKEN if needed."
    fi

install:
  - moodle-plugin-ci install -vvv

script:
  - make test-phpunit

  # This is basically "integration" testing.
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci validate
  - moodle-plugin-ci savepoints
  - moodle-plugin-ci mustache
  - moodle-plugin-ci grunt || [ "$MOODLE_BRANCH" == 'MOODLE_38_STABLE' ]
  - moodle-plugin-ci phpdoc
  - moodle-plugin-ci phpunit --verbose --coverage-text --fail-on-warning
  - moodle-plugin-ci behat --profile default
  - moodle-plugin-ci behat --profile chrome

jobs:
  include:
    - stage: Tests
      php: 7.3
      before_install: skip
      install:
        - make init
      script:
        - make validate
    - stage: Integration tests
    - php: 7.4
      env: MOODLE_BRANCH=MOODLE_401_STABLE
    - php: 7.4
      env: MOODLE_BRANCH=MOODLE_400_STABLE
    - php: 7.4
      env: MOODLE_BRANCH=MOODLE_311_STABLE
    - php: 7.4
      env: MOODLE_BRANCH=MOODLE_310_STABLE
    - php: 7.4
      env: MOODLE_BRANCH=MOODLE_39_STABLE
    - php: 7.4
      env: MOODLE_BRANCH=MOODLE_38_STABLE
