language: php

addons:
  postgresql: "9.5"

services:
  - mysql
  - postgresql
  - docker

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

php:
 - 7.3

env:
  global:
    - IGNORE_PATHS=ignore
    - IGNORE_NAMES=ignore_name.php
    - MUSTACHE_IGNORE_NAMES=broken.mustache
    - DB=pgsql
    - MOODLE_BRANCH=master

before_install:
  - phpenv config-rm xdebug.ini
  - nvm install 14.0.0
  - nvm use 14.0.0
  - make init
  # Mimic how a Moodle plugin would be run.
  - cp -R tests/Fixture/moodle-local_travis ../moodle-local_travis
  - export PATH="$(cd bin; pwd):$(cd vendor/bin; pwd):$PATH"
  - export TRAVIS_BUILD_DIR=$(cd ../moodle-local_travis; pwd)
  # Start Selenium Standalone with Chrome.
  - docker run -d -p 127.0.0.1:4444:4444 --net=host --shm-size=2g -v $HOME/build/moodle:$HOME/build/moodle selenium/standalone-chrome:3

install:
  - moodle-plugin-ci install

script:
  - make test-phpunit

  # This is basically "integration" testing.
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci validate
  - moodle-plugin-ci savepoints
  - moodle-plugin-ci mustache
  - moodle-plugin-ci grunt || [ "$MOODLE_BRANCH" != 'master' -a "$MOODLE_BRANCH" != 'MOODLE_39_STABLE' ]
  - moodle-plugin-ci phpdoc
  - moodle-plugin-ci phpunit --coverage-text
  - moodle-plugin-ci behat --profile chrome

jobs:
  include:
    - stage: Tests
      php: 7.3
      addons: skip
      install:
        - make init
      script:
        - make validate
    - stage: Integration tests
    - php: 7.3
      env: MOODLE_BRANCH=MOODLE_39_STABLE
    - php: 7.3
      env: MOODLE_BRANCH=MOODLE_38_STABLE
    - php: 7.3
      env: MOODLE_BRANCH=MOODLE_37_STABLE
    - php: 7.2
      env: MOODLE_BRANCH=MOODLE_35_STABLE
